oldSchema = jsondecode(fileread('C:\InovaFiscaliza\appColeta\src\config\ReceiverLib.json'));

newSchema = struct( ...
    'family', {}, ...
    'name', {}, ...
    'tag', {}, ...
    'band', {}, ...
    'image', {}, ...
    'connection', {}, ...
    'communication', {}, ...
    'features', {} ...
);

parametersMapping = {
    'TraceMode',        'traceMode'; 
    'AverageMode',      'averageMode'; 
    'AverageCount',     'averageCount'; 
    'Detector',         'detector'; 
    'LevelUnit',        'levelUnit'; 
    'FreqStart',        'freqStart'; 
    'FreqStop',         'freqStop'; 
    'DataPoints',       'dataPoints'; 
    'StepWidth',        'stepWidth'; 
    'ResolutionMode',   'resolutionMode';
    'ResolutionValue',  'resolutionValue'; 
    'Selectivity',      'selectivity'; 
    'SensitivityMode',  'sensitivityMode'; 
    'Preamp',           'preamp'; 
    'AttenuationMode',  'attenuationMode'; 
    'AttenuationValue', 'attenuationValue'; 
    'SampleTimeMode',   'sampleTimeMode'; 
    'SampleTimeValue', 'sampleTimeValue'; 
    'minFreqRange',    'minFreqRange'; 
    'maxFreqRange',     'maxFreqRange';
    'VideoBandwidth',   'videoBandWidth'; 
    'FreqCenter',       'freqCenter'; 
    'FreqSpan',         'freqSpan'; 
    'DF_SquelchMode',   'dfSquelchMode'; 
    'DF_SquelchValue',  'dfSquelchValue'; 
    'DF_MeasTime',      'dfMeasTime'
};


for ii = 1:numel(oldSchema)
    newSchema(ii).family         = oldSchema(ii).Family;
    newSchema(ii).name           = oldSchema(ii).Name;
    newSchema(ii).tag            = oldSchema(ii).Tag;
    newSchema(ii).band           = oldSchema(ii).Band;
    newSchema(ii).image          = oldSchema(ii).Image;

    newSchema(ii).connection = struct( ...
        'types',                  {oldSchema(ii).connectType}, ...
        'defaultPort',             oldSchema(ii).connectPort, ...
        'traceData', struct( ...
            'acquisitionMode', 'polling', ...
            'dataType', 'level' ...
        ) ...
    );

    queryStatus = oldSchema(ii).scpiStatus;
    if isempty(queryStatus)
        queryStatus = '';
    end

    newSchema(ii).communication = struct( ...
        'legacy', struct( ...
            'initReset',           oldSchema(ii).scpiReset, ...
            'initStartup',         oldSchema(ii).StartUp, ...
            'initSweepMode',       'INITiate:CONTinuous %SweepMode%', ...
            'setBandConfig',       oldSchema(ii).scpiGeneral, ...
            'setAttenuation',      oldSchema(ii).scpiAttenuation, ...
            'setVideoBandWidth',   oldSchema(ii).scpiVBW_Options, ...
            'queryIdentification', '*IDN?', ...
            'queryStatus',         queryStatus, ...
            'queryBandConfig',     oldSchema(ii).scpiQuery, ...
            'queryAttenuation',    oldSchema(ii).scpiQuery_Attenuation, ...
            'fetchTraceData',      oldSchema(ii).scpiTraceData, ...
            'fetchGpsData',        oldSchema(ii).scpiGPS ...
        ), ...
        'set', struct( ...
            'step', {}, ...
            'commands', {} ...
        ), ...
        'query', struct( ...
            'identification',      '*IDN?', ...
            'status',              queryStatus, ...
            'bandConfig',          oldSchema(ii).scpiQuery, ...
            'attenuation',         oldSchema(ii).scpiQuery_Attenuation ...
        ), ...
        'fetch', struct( ...
            'traceData',           oldSchema(ii).scpiTraceData, ...
            'gpsData',             oldSchema(ii).scpiGPS ...
        ), ...
        'parameters', struct( ...
            'name', {}, ...
            'write', {}, ...
            'read', {}, ...
            'requireMatch', {} ...
        ) ...
    );

    requiresAverageModeFor = [];
    if ~isempty(oldSchema(ii).AverageMode_Values)
        requiresAverageModeFor = oldSchema(ii).AverageMode_Values;
    end

    newSchema(ii).features = struct( ...
        'attenuationValues',       oldSchema(ii).Attenuation_Values, ...
        'levelUnits',              oldSchema(ii).LevelUnit_Values, ...
        'stepWidths',              oldSchema(ii).StepWidth_Values, ...
        'resolutions',             oldSchema(ii).Resolution_Values, ...
        'videoBandWidths',         oldSchema(ii).VBW_Values, ...
        'dataPoints',              oldSchema(ii).DataPoints_Limits, ...
        'detector', struct( ...
            'items',               oldSchema(ii).Detector_Items, ...
            'values',              oldSchema(ii).Detector_Values ...
        ), ...
        'sweepMode', struct( ...
            'items',               oldSchema(ii).SyncOptions, ...
            'values',              'OFF' ...
        ), ...
        'traceMode', struct( ...
            'items',               'ClearWrite,Average,MaxHold,MinHold', ...
            'values',              oldSchema(ii).Trace_Values, ...
            'requiresAverageModeFor', requiresAverageModeFor ...
        ) ...
    );

    newSchema(ii).communication.parameters(1).name         = 'reset';
    newSchema(ii).communication.parameters(1).write        = oldSchema(ii).scpiReset;
    newSchema(ii).communication.parameters(1).read         = '';
    newSchema(ii).communication.parameters(1).requireMatch = false;

    newSchema(ii).communication.parameters(2).name         = 'startup';
    newSchema(ii).communication.parameters(2).write        = oldSchema(ii).StartUp;
    newSchema(ii).communication.parameters(2).read         = '';
    newSchema(ii).communication.parameters(2).requireMatch = false;

    newSchema(ii).communication.parameters(3).name         = 'sweepMode';
    newSchema(ii).communication.parameters(3).write        = 'INITiate:CONTinuous %SweepMode%';
    newSchema(ii).communication.parameters(3).read         = '';
    newSchema(ii).communication.parameters(3).requireMatch = false;

    parametersWrite = strsplit(oldSchema(ii).scpiGeneral, ';:');
    parametersRead  = strsplit(oldSchema(ii).scpiQuery, ';:');
    parameterNames  = parametersMapping(oldSchema(ii).scpiQuery_IDs, 2);
    
    for jj = 1:numel(oldSchema(ii).scpiQuery_IDs)
        index = oldSchema(ii).scpiQuery_IDs(jj);

        parameterWriteIndex = find(contains(parametersWrite, replace(parametersRead{jj}, '?', ''), "IgnoreCase", true), 1);
        if ~isempty(parameterWriteIndex)
            parameterWrite = parametersWrite{parameterWriteIndex};
        else
            parameterWrite = oldSchema(ii).scpiGeneral;
        end

        newSchema(ii).communication.parameters(end+1).name       = parametersMapping{index, 2};
        newSchema(ii).communication.parameters(end).read         = parametersRead{jj};
        newSchema(ii).communication.parameters(end).write        = parameterWrite;        
        newSchema(ii).communication.parameters(end).requireMatch = false;
    end

    [~, sortIndexes] = sort({newSchema(ii).communication.parameters.name});
    newSchema(ii).communication.parameters = newSchema(ii).communication.parameters(sortIndexes);

    newSchema(ii).communication.set(1:2) = struct( ...
        'step', {'initialization', 'acquisition'}, ...
        'commands', struct( ...
            'name', {}, ...
            'parameterNames', {}, ...
            'mandatory', {}, ...
            'postDelay', {} ...
        ) ...
    );

    newSchema(ii).communication.set(1).commands(1) = struct( ...
        'name', 'reset', ...
        'parameterNames', {{'reset'}}, ...
        'mandatory', false, ...
        'postDelay', oldSchema(ii).ResetPause ...
    );

    newSchema(ii).communication.set(1).commands(2) = struct( ...
        'name', 'startup', ...
        'parameterNames', {{'startup'}}, ...
        'mandatory', true, ...
        'postDelay', 0 ...
    );

    newSchema(ii).communication.set(1).commands(3) = struct( ...
        'name', 'sweepMode', ...
        'parameterNames', {{'sweepMode'}}, ...
        'mandatory', true, ...
        'postDelay', 0 ...
    );

    newSchema(ii).communication.set(2).commands(1) = struct( ...
        'name', 'bandConfig', ...
        'parameterNames', {parameterNames}, ...
        'mandatory', true, ...
        'postDelay', oldSchema(ii).BandPause ...
    );

    newSchema(ii).communication.set(2).commands(2) = struct( ...
        'name', 'attenuationValue', ...
        'parameterNames', {{'attenuationValue'}}, ...
        'mandatory', false, ...
        'postDelay', 0 ...
    );

    newSchema(ii).communication.set(2).commands(3) = struct( ...
        'name', 'videoBandWidth', ...
        'parameterNames', {{'videoBandWidth'}}, ...
        'mandatory', false, ...
        'postDelay', 0 ...
    );
end

writematrix(jsonencode(newSchema, "PrettyPrint", true), 'novoReceiverLib.json', 'Encoding', 'utf-8', 'FileType', 'text', 'QuoteStrings', 'none')