classdef Task < matlab.mixin.Copyable

    %---------------------------------------------------------------------%
    % ## model.Task ##
    %
    % Representa uma tarefa de monitoração (na fila, em andamento ou já
    % finalizada) gerenciada pelo appColeta. Essa classe substitui a antiga
    % "class.specClass", preservando a mesma estrutura de propriedades para
    % manter compatibilidade com as funções auxiliares que a consomem via
    % "duck typing" (sem checagem de classe): class.RFlookBinLib, class.EB500Lib,
    % class.maskLib, fcn.FindPeaks, fcn.RevisitFactors, fcn.receiverConfig_General
    % e fcn.receiverConfig_SpecificBand.
    %
    % A lista de tarefas em execução é mantida em model.TaskController.Tasks.
    % A propriedade "app.specObj" (winAppColeta_exported.m) é apenas uma
    % referência de conveniência (Dependent) para esse array.
    %
    % app.TaskController.Tasks = model.Task.empty;
    %---------------------------------------------------------------------%

    properties
        TaskId
        ReceiverId

        TaskSpec = class.taskClass.empty                                    % See "auxApp.winAddTask.mlapp"
        Timing   = struct('createdAt', '', ...                              % Datestring data type - Format: '24/02/2023 14:00:00'
                          'startedAt', NaT, ...                             % Datetime data type
                          'endedAt',   NaT, ...                             % Datetime data type
                          'startupAt', NaT)                                 % Datetime data type

        Connections = struct('receiver', [], ...                           % Handle to Receiver
                             'stream',   [], ...                           % Handle to UDP socket (generated by R&S EB500)
                             'gps',      [])                               % Handle to GPS

        GPSLastFix       = struct('Status', 0, 'Latitude', -1, 'Longitude', -1, 'TimeStamp', '')
        ReceiverCommands = struct('reset', {}, 'startup', {}, 'sync', {}, 'query', {}, 'data', {})
        Bands            = class.bandClass.empty                           % See "fcn.receiverConfig_SpecificBand.m"

        RetryPolicy = struct('receiver', struct('failureCount', 0, 'firstFailureAt', NaT, 'lastFailureAt', NaT), ...
                             'gps',      struct('failureCount', 0, 'firstFailureAt', NaT, 'lastFailureAt', NaT))
        Status      = ''                                                    % 'Na fila' | 'Em andamento' | 'Concluída' | 'Cancelada' | 'Erro'
        LogEntries  = struct('level', {}, 'timestamp', {}, 'message',  {})
    end


    methods
        %-----------------------------------------------------------------%
        function [obj, errorMsg] = AddOrEditTask(obj, infoEdition, newTask, EMSatObj, ERMxObj)
            switch infoEdition.type
                case 'new'
                    idx = numel(obj)+1;
                    obj(idx).TaskId = idx;
                    obj(idx).Timing.createdAt = datestr(now, 'dd/mm/yyyy HH:MM:SS');

                case 'edit'
                    idx = infoEdition.idx;
            end

            obj(idx).TaskSpec = newTask;

            obj(idx).Connections.receiver = newTask.Receiver.Handle;
            obj(idx).Connections.stream   = newTask.Streaming.Handle;
            obj(idx).Connections.gps      = newTask.GPS.Handle;

            obj(idx).ReceiverId = newTask.Receiver.Handle.UserData.IDN;

            obj(idx).Timing.startedAt = datetime(newTask.Script.Observation.BeginTime, 'InputFormat', 'dd/MM/yyyy HH:mm:ss');
            obj(idx).Timing.endedAt   = datetime(newTask.Script.Observation.EndTime,   'InputFormat', 'dd/MM/yyyy HH:mm:ss');

            obj.startup_lastGPS(idx, newTask.Script.GPS);
            errorMsg = obj.startup_ReceiverTest(idx, EMSatObj, ERMxObj);
        end

        %-----------------------------------------------------------------%
        function instr = Instrument(obj)
            instr = struct( ...
                'Type', obj.TaskSpec.Receiver.Selection.Type{1}, ...
                'Tag', obj.TaskSpec.Receiver.Config.Tag{1}, ...
                'Parameters', jsondecode(obj.TaskSpec.Receiver.Selection.Parameters{1}) ...
            );
        end
    end


    methods (Access = protected)
        %-----------------------------------------------------------------%
        function startup_lastGPS(obj, idx, GPS)
            if strcmp(GPS.Type, 'Manual')
                obj(idx).GPSLastFix.Status    = -1;
                obj(idx).GPSLastFix.Latitude  = GPS.Latitude;
                obj(idx).GPSLastFix.Longitude = GPS.Longitude;
            end
            obj(idx).GPSLastFix.TimeStamp = obj(idx).Timing.createdAt;
        end


        %-----------------------------------------------------------------%
        function errorMsg = startup_ReceiverTest(obj, idx, EMSatObj, ERMxObj)
            errorMsg = '';

            try
                fcn.receiverConfig_General(obj, idx);
                warnMsg = fcn.receiverConfig_SpecificBand(obj, idx, EMSatObj, ERMxObj);
                obj(idx).Status = 'Na fila';

                if ~isempty(warnMsg)
                    obj(idx).LogEntries(end+1) = struct('level', 'warning', 'timestamp', obj(idx).Timing.createdAt, 'message', strjoin(warnMsg, '\n\n'));
                end
                obj(idx).LogEntries(end+1) = struct('level', 'task', 'timestamp', char(datetime('now')), 'message', 'Incluída na fila a tarefa.');

            catch ME
                fprintf('%s\n', jsonencode(ME))
                errorMsg = ME.message;

                if isempty(obj(idx).Bands)
                    obj(idx) = [];
                else
                    obj(idx).Status = 'Erro';
                    obj(idx).LogEntries(end+1) = struct('level', 'error', 'timestamp', char(datetime('now')), 'message', errorMsg);
                end
            end
        end
    end
end